[package]
name = "work_amounts_setter"
version = "0.2.0"
edition = "2021"

[dependencies]
http = "0.2"
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
xml-doc = "0.2.0"